#!/usr/bin/env node

if(require('module')._extensions['.coffee']===undefined){
  // Avoid conflicts with another version
  require('coffee-script/register');
}
module.exports= require('./gulp-jsfy.coffee');